name: MinecraftPackageTool
version: ${version}
main: dev.titanlabs.mpt.mc.bukkit.PackageBukkitPlugin
api-version: 1.16

commands:
  mpt:
    aliases: []
    description: "The main command of the plugin."

permissions:
  mpt.admin:
    description: "The main permission of the plugin."